HIDER_CAN_MOVE = True
SEEKER_VIEW_RANGE = 3
HIDER_VIEW_RANGE = 2
HIDER_PING_RANGE = 3

TIME_LIMIT = 20
STEP_INTERVAL = 50 # ms between each steps
DEFAULT_POINTS = 100

IN_GAME_FONT_SIZE = 20
GAME_OVER_FONT_SIZE = 64